site_name: Lake Afton Public Observatory
site_description: Object and Program notes for use during the public program at the Lake Afton Public Observatory's 16-inch telescope
site_author: Chris Ketron
copyright: '&copy; 2023 Lake Afton Public Observatory'
site_url: http://lake-afton-presenter-notes.readthedocs.io/en/latest/
repo_url: https://github.com/caketron/lake-afton-presenter-notes.git
theme: slate
extra_css:
  - 'css/nightvision.css'
extra_javascript:
  - 'js/whatsup.js'
nav:
  - Home: 'index.md'

  - Notes:
      - Notes: 'notes.md'
      - About: 'about.md'
      - Objects: 'object-availability.md'
      - Telescope:
          - 'Telescope Specs': 'telescope/telescope.md'
          - 'Telescope Operations': 'telescope/telescope-operation.md'
          - 'Cloudy Night Tour': 'telescope/telescope-cloudy.md'
          - 'Common Formulas': 'telescope/telescope-formula.md'
      - Greek Letters: 'greek.md'
      - Reference Sites: 'reference.md'
      - Image Credits: 'img/image-credits.md'
      - What's Up: 'whats-up.md'

  - Objects:
      - Solar System:
          - 'Sun': 'solar-system/sun.md'
          - 'Mercury': 'solar-system/mercury.md'
          - 'Venus': 'solar-system/venus.md'
          - Earth:
              - 'Clouds': 'solar-system/clouds.md'
              - The Moon:
                  - 'Overview': 'solar-system/moon.md'
                  - 'Mare': 'solar-system/moon-mare.md'
                  - 'Craters': 'solar-system/moon-craters.md'
                  - 'Mountains': 'solar-system/moon-mountains.md'
                  - 'Other Features': 'solar-system/moon-other-features.md'
          - 'Mars': 'solar-system/mars.md'
          - 'Jupiter': 'solar-system/jupiter.md'
          - 'Saturn': 'solar-system/saturn.md'
          - 'Uranus': 'solar-system/uranus.md'
          - 'Neptune': 'solar-system/neptune.md'
          - Asteroids:
              - 'Asteroids': 'solar-system/asteroids/!asteroid-info.md'
              - '4 Vesta': 'solar-system/asteroids/4vesta.md'
              - 'Ceres': 'solar-system/asteroids/ceres.md'
          - Comets:
              - 'Comets': 'solar-system/comets/!comet-info.md'
              - 'Comet Encke': 'solar-system/comets/comet-encke.md'

          - Space Missions:
              - 'Missions': 'solar-system/space-missions/!missions-info.md'

      - Stars:
          - Red:
              - Giant:
                  - 'Red Giant Stars': 'stars/red/giant/!red-giant-stars.md'
                  - 'Aldebaran': 'stars/red/giant/aldebaran.md'
                  - 'Arcturus': 'stars/red/giant/arcturus.md'
                  - 'Capella': 'stars/red/giant/capella.md'
                  - 'Pollux': 'stars/red/giant/pollux.md'
                  - 'R Leporis': 'stars/red/giant/r-leporis.md'
                  - 'S Cephei': 'stars/red/giant/s-cephei.md'
              - Supergiant:
                  - 'Red Supergiant Stars': 'stars/red/supergiant/!red-supergiant-stars.md'
                  - 'Antares': 'stars/red/supergiant/antares.md'
                  - 'Betelgeuse': 'stars/red/supergiant/betelgeuse.md'
                  - 'Mu Cephei': 'stars/red/supergiant/mu-cephei.md'
          - Yellow:
              - 'Yellow Stars': 'stars/yellow/!yellow-stars.md'
              - 'Beta Canum Venaticorum': 'stars/yellow/beta-canum-venaticorum.md'
              - 'Beta Comae Berenices': 'stars/yellow/beta-comae-berenices.md'
              - 'Procyon': 'stars/yellow/procyon.md'
              - 'Xi Ursae Majoris': 'stars/yellow/xi-ursae-majoris.md'
          - Blue:
              - 'Blue Stars': 'stars/blue/!blue-stars.md'
              - 'Altair': 'stars/blue/altair.md'
              - 'Castor': 'stars/blue/castor.md'
              - 'Deneb': 'stars/blue/deneb.md'
              - 'Fomalhaut': 'stars/blue/fomalhaut.md'
              - 'Regulus': 'stars/blue/regulus.md'
              - 'Rigel': 'stars/blue/rigel.md'
              - 'Sirius': 'stars/blue/sirius.md'
              - 'Spica': 'stars/blue/spica.md'
              - 'Vega': 'stars/blue/vega.md'
          - Contrast Multiple:
              - 'Contrast Multiple': 'stars/contrast-multiple/!contrast-multiple-star-info.md'
              - '32 Eridani': 'stars/contrast-multiple/32eridani.md'
              - '95 Hercules': 'stars/contrast-multiple/95hercules.md'
              - 'Gamma Andromedae': 'stars/contrast-multiple/gamma-andromedae.md'
              - 'Iota Canceri': 'stars/contrast-multiple/iota-cancri.md'
              - 'Xi Bootis': 'stars/contrast-multiple/xi-bootis.md'
          - Contrast Optical Double:
              - 'Contrast Optical Double': 'stars/contrast-optical-double/!contrast-optical-double-star-info.md'
              - '24 Coma Berenices': 'stars/contrast-optical-double/24comae-berenices.md'
              - 'Albireo': 'stars/contrast-optical-double/albireo.md'
          - non-Contrast Multiple:
              - 'non-Contrast Multiple': 'stars/non-contrast-multiple/!non-contrast-multiple-star-info.md'
              - '61 Cygni': 'stars/non-contrast-multiple/61-cygni.md'
              - 'Beta Lyrae': 'stars/non-contrast-multiple/beta-lyrae.md'
              - 'Beta Monocerotis': 'stars/non-contrast-multiple/beta-mon.md'
              - 'Gamma Arietis': 'stars/non-contrast-multiple/gamma-arietis.md'
              - 'Gamma Leonis': 'stars/non-contrast-multiple/gamma-leonis.md'
              - 'Sigma Orionis': 'stars/non-contrast-multiple/sigma-orionis.md'
              - 'Xi Cancri': 'stars/non-contrast-multiple/xi-cancri.md'
              - 'Zeta Bootis': 'stars/non-contrast-multiple/zeta-bootis.md'
              - 'Zeta Cancri': 'stars/non-contrast-multiple/zeta-cancri.md'
              - 'Zeta Ursae Majoris': 'stars/non-contrast-multiple/zeta-ursae-majoris.md'
          - non-Contrast Optical Double:
              - 'non-Contrast Optical Double': 'stars/non-contrast-optical-double/!non-contrast-optical-double-star-info.md'
              - 'Alpha Canum Venaticorum': 'stars/non-contrast-optical-double/alpha-canum-venaticorum.md'
              - 'Alpha Capricorni': 'stars/non-contrast-optical-double/alpha-capricorni.md'
              - 'Beta Scorpii': 'stars/non-contrast-optical-double/beta-scorpii.md'
              - 'Delta Cephei': 'stars/non-contrast-optical-double/delta-cephei.md'
              - 'Epsilon Lyrae': 'stars/non-contrast-optical-double/epsilon-lyrae.md'
              - 'Gamma Delphini': 'stars/non-contrast-optical-double/gamma-delphini.md'
          - with Planets:
              - '47 Ursae Majoris': 'stars/with-planets/47-ursae-majoris.md'

      - Star Clusters:
          - Globular:
              - Globular Clusters: 'star-clusters/globular/!globular-cluster-info.md'
              - M2: 'star-clusters/globular/m2.md'
              - M3: 'star-clusters/globular/m3.md'
              - M13: 'star-clusters/globular/m13.md'
              - M15: 'star-clusters/globular/m15.md'
              - M79: 'star-clusters/globular/m79.md'
              - M92: 'star-clusters/globular/m92.md'
          - Open:
              - Open Clusters: 'star-clusters/open/!open-cluster-info.md'
              - h and Chi Persei: 'star-clusters/open/hxpersei.md'
              - M11: 'star-clusters/open/m11.md'
              - M16: 'star-clusters/open/m16.md'
              - M24: 'star-clusters/open/m24.md'
              - M25: 'star-clusters/open/m25.md'
              - M35: 'star-clusters/open/m35.md'
              - M36: 'star-clusters/open/m36.md'
              - M37: 'star-clusters/open/m37.md'
              - M44: 'star-clusters/open/m44.md'
              - M45: 'star-clusters/open/m45.md'
              - M46: 'star-clusters/open/m46.md'
              - M47: 'star-clusters/open/m47.md'
              - M52: 'star-clusters/open/m52.md'
              - NGC457: 'star-clusters/open/ngc457.md'
              - NGC663: 'star-clusters/open/ngc663.md'
              - NGC6530: 'star-clusters/open/ngc6530.md'

      - Galaxies:
          - Elliptical:
              - Elliptical Galaxies: 'galaxies/elliptical/!elliptical-galaxy-info.md'
              - M49: 'galaxies/elliptical/m49.md'
              - M84: 'galaxies/elliptical/m84.md'
              - M85: 'galaxies/elliptical/m85.md'
              - M87: 'galaxies/elliptical/m87.md'
          - Irregular:
              - Irregular Galaxies: 'galaxies/irregular/!irregular-galaxy-info.md'
              - M82: 'galaxies/irregular/m82.md'
          - Spiral:
              - Spiral Galaxies: 'galaxies/spiral/!spiral-galaxy-info.md'
              - M31: 'galaxies/spiral/m31.md'
              - M51: 'galaxies/spiral/m51.md'
              - M65: 'galaxies/spiral/m65.md'
              - M66: 'galaxies/spiral/m66.md'
              - M81: 'galaxies/spiral/m81.md'
              - M94: 'galaxies/spiral/m94.md'
              - M104: 'galaxies/spiral/m104.md'
              - M106: 'galaxies/spiral/m106.md'
              - NGC7331: 'galaxies/spiral/ngc7331.md'

      - Nebulae:
          - Diffuse:
              - Diffuse Nebulae: 'nebulae/diffuse/!diffuse-nebulae-info.md'
              - M17: 'nebulae/diffuse/m17.md'
              - M42: 'nebulae/diffuse/m42.md'
          - Planetary:
              - Planetary Nebulae: 'nebulae/planetary/!planetary-nebulae-info.md'
              - M27: 'nebulae/planetary/m27.md'
              - M57: 'nebulae/planetary/m57.md'
              - NGC2392: 'nebulae/planetary/ngc2392.md'
              - NGC3242: 'nebulae/planetary/ngc3242.md'
              - NGC6826: 'nebulae/planetary/ngc6826.md'
          - Supernovae Remnants:
              - Supernova Remnant: 'nebulae/supernovae-remnants/!supernova-remnant-info.md'
              - M1: 'nebulae/supernovae-remnants/m1.md'

  - Programs:
      - Summer:
          - Life of a Star: 'programs/summer/life-of-a-star.md'
          - Sizing Up Saturn: 'programs/summer/sizing-up-saturn.md'
      - Fall:
          - Stars of Astronomy: 'programs/fall/stars-of-astronomy.md'
      - Winter:
          - Stars, Stars and More Stars: 'programs/winter/stars-stars-and-more-stars.md'
